service: chromeless-serverless

custom:
  stage: ${env:STAGE}
  debug: "*"
  awsIotHost: ${env:AWS_IOT_HOST}
  bucketName: ${env:AWS_S3_BUCKET_NAME}
  keyPrefix: ${env:AWS_S3_KEY_PREFIX}
  region: ${env:REGION}
  chrome:
    functions:
      - run

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  environment:
    DEBUG: ${self:custom.debug}
    AWS_IOT_HOST: ${self:custom.awsIotHost}
  apiKeys:
    - ${self:custom.stage}-chromeless-session-key
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "iot:Connect"
        - "iot:Publish"
        - "iot:Subscribe"
        - "iot:Receive"
        - "iot:GetThingShadow"
        - "iot:UpdateThingShadow"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - s3:PutObject
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - ${self:custom.bucketName}
            - "/"
            - ${self:custom.keyPrefix}
            - "*"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-chrome
  - serverless-offline

functions:
  run:
    memorySize: 1536
    timeout: 300
    handler: src/run.default
    events:
      - iot:
          sql: "SELECT * FROM 'chrome/new-session'"
    environment:
      CHROMELESS_S3_BUCKET_NAME: ${self:custom.bucketName}
      CHROMELESS_S3_OBJECT_KEY_PREFIX: ${self:custom.keyPrefix}
      CHROMELESS_S3_BUCKET_URL:
        Fn::Join:
          - ""
          - - ${self:custom.bucketName}
            - ".s3.amazonaws.com"
  version:
    memorySize: 128
    handler: src/version.default
    events:
    - http:
        path: /version
        method: GET
  session:
    memorySize: 128
    timeout: 10
    handler: src/session.default
    events:
      - http:
          method: OPTIONS
          path: /
          private: true
      - http:
          method: GET
          path: /
          private: true
  disconnect:
    memorySize: 256
    handler: src/disconnect.default
    timeout: 10
    events:
      - iot:
          sql: "SELECT * FROM 'chrome/last-will'"

resources:
  Resources:
    RunLogGroup:
      Properties:
        RetentionInDays: 7
    VersionLogGroup:
      Properties:
        RetentionInDays: 7
    SessionLogGroup:
      Properties:
        RetentionInDays: 7
    DisconnectLogGroup:
      Properties:
        RetentionInDays: 7
